name: "Generate Ascii"

on: push

jobs:
  shell_script_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Executing shell script
      run: |
        chmod +x .github/workflows/ascii.sh
        .github/workflows/ascii.sh