name: Triggering Workflow

on:
  schedule:
    - cron: "*/1 * * * *"

jobs:
  trigger-flow:
    runs-on: ubuntu-latest  
    steps:                  
      - name: echo hello world
        run: echo "hello world"
      - name: run ls
        run: ls
