# name: Matrix Configuration

# on:
#   push:

# jobs:
#     deploy-on-ubuntu:
#       runs-on: ubuntu-latest
#       steps:
#         - name: Echo docker details
#           run: docker info

#     deploy-on-windows:
#         runs-on: windows-latest
#         steps:
#           - name: echo docker details
#             run: docker info

name: Matrix Configuration
on:
  push:

jobs:
  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: echo docker details
        run: docker info
      
      - name: docker ps
        run: docker ps